//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cosechas
    {
        public int cosec_id { get; set; }
        public string cosec_fecha { get; set; }
        public Nullable<int> Con_Id { get; set; }
        public Nullable<int> cosec_preciodia { get; set; }
        public Nullable<int> tc_id { get; set; }
    
        public virtual contratos contratos { get; set; }
        public virtual TipoCosechas TipoCosechas { get; set; }
    }
}
