//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCosechas
    {
        public int dc_id { get; set; }
        public Nullable<int> cosec_id { get; set; }
        public Nullable<int> dc_peso { get; set; }
    
        public virtual Cosechas Cosechas { get; set; }
    }
}
