//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposCuarteles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GruposCuarteles()
        {
            this.GrupoCuartelesDetalle = new HashSet<GrupoCuartelesDetalle>();
        }
    
        public int gc_id { get; set; }
        public Nullable<int> cuar_id { get; set; }
        public Nullable<int> gc_nom { get; set; }
        public Nullable<int> ConJefe_id { get; set; }
    
        public virtual contratos contratos { get; set; }
        public virtual Cuarteles Cuarteles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoCuartelesDetalle> GrupoCuartelesDetalle { get; set; }
    }
}
