//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario_laboral
    {
        public int Hl_Id { get; set; }
        public Nullable<int> Car_Id { get; set; }
        public string Hl_Titulo { get; set; }
        public string Hl_Descripcion { get; set; }
        public Nullable<System.DateTime> Hl_Inicio { get; set; }
        public Nullable<System.DateTime> Hl_Termino { get; set; }
        public string Hl_ColorTema { get; set; }
        public Nullable<bool> Hl_TodoDia { get; set; }
    
        public virtual cargos cargos { get; set; }
    }
}
