//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginPrivilegiosCuentas
    {
        public int lpc_id { get; set; }
        public Nullable<int> log_id { get; set; }
        public Nullable<int> pc_id { get; set; }
    
        public virtual PrivilegiosCuentas PrivilegiosCuentas { get; set; }
        public virtual login login { get; set; }
    }
}
