//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public login()
        {
            this.LoginPrivilegiosCuentas = new HashSet<LoginPrivilegiosCuentas>();
        }
    
        public int log_id { get; set; }
        public int Emp_Id { get; set; }
        public string Per_Rut { get; set; }
        public string Id { get; set; }
        public Nullable<int> Sub_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual empresas empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginPrivilegiosCuentas> LoginPrivilegiosCuentas { get; set; }
        public virtual personas personas { get; set; }
    }
}
