//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;

    public partial class SolicitudDetalleQr
    {
        public int sdqr_id { get; set; }
        public Nullable<int> sqr_id { get; set; }
        public Nullable<int> Con_id { get; set; }
        public string nombre { get; set; }
        public byte[] formato { get; set; }
        public bool estado { get; set; }

        public virtual contratos contratos { get; set; }
        public virtual SolicitudesQr SolicitudesQr { get; set; }
    }
}
