//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subempresa_cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subempresa_cargo()
        {
            this.subempresa_cargo_horario = new HashSet<subempresa_cargo_horario>();
        }
    
        public int Subempcar_id { get; set; }
        public Nullable<int> Sub_Id { get; set; }
        public Nullable<int> Car_Id { get; set; }
    
        public virtual cargos cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subempresa_cargo_horario> subempresa_cargo_horario { get; set; }
        public virtual subempresas subempresas { get; set; }
    }
}
