//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subempresa_cargo_horario
    {
        public int Sch_Id { get; set; }
        public Nullable<int> Subempcar_id { get; set; }
        public Nullable<int> Hl_Id { get; set; }
    
        public virtual horario_laboral horario_laboral { get; set; }
        public virtual subempresa_cargo subempresa_cargo { get; set; }
    }
}
